### ISSUE TITLE
I compiled the binary (Linux). And loaded into GDNativeCPP project. Do I create the nodes myself or does the library creates everything on it's own? 

### ISSUE THREAD

**Issue by h1s0k429a** [tterrasson/liquid-simulator-godot#2]
What do I create, add or modify in the CPP project that I got from the GDnativeCPP project?

**Comment by tterrasson** [comment]
I've updated the README and added a demo project to better explain how to use the plugin (you will have to rebuild it).

**Comment by h1s0k429a** [comment]
Thank you that helped a lot. Also would you be ok if I contribute more to this project and polish it here and there?

**Comment by tterrasson** [comment]
Sure! I will gladly merge any enhancement :)
